/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ../gaming_room/scene.gltf 
Author: Shabeer Ahmed (https://sketchfab.com/shabeer113ahmed)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-room-47f1263d4e2843f08060c680901fb9cd
Title: Gaming Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.909, 1.245, -2.842]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001}>
        <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_8.geometry} material={materials.Mat3} position={[0.001, -17.84, 46.282]} rotation={[-Math.PI / 2, 0, 0]} scale={[240, 100, 300]} />
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[240, 100, 300]}>
            <mesh geometry={nodes.Object_11_1.geometry} material={materials.Mat1} />
            <mesh geometry={nodes.Object_13_1.geometry} material={materials.Mat2} />
          </group>
        </group>
      </group>
      <group position={[-5.241, 2.646, 3.507]} rotation={[-Math.PI / 2, 0, 0]} scale={1.596}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_19_1.geometry} material={materials['Material.018']} position={[-0.161, 0.721, 0]} scale={[0.063, 0.096, 0.096]} />
          <group position={[-0.161, 0.717, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.144, 0.064, 0.144]}>
            <mesh geometry={nodes.Object_22_1.geometry} material={materials.plastic} />
            <mesh geometry={nodes.Object_24_1.geometry} material={materials.screen} />
          </group>
        </group>
      </group>
      <group position={[-4.251, 2.649, 5.449]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.304}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.644, 0.114, -0.655]}>
            <group position={[-0.001, 0, 0.003]}>
              <mesh geometry={nodes.Object_34.geometry} material={materials.blueneon} />
              <mesh geometry={nodes.Object_35.geometry} material={materials.blueneon} />
            </group>
            <mesh geometry={nodes.Object_30.geometry} material={materials.whitebase} position={[0.106, -0.087, 0.486]} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.blackbase} position={[-0.184, -0.017, 0.234]} />
          </group>
        </group>
      </group>
      <group position={[-4.481, 2.728, 2.256]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.019']} />
      </group>
      <group position={[-4.461, 2.732, 2.253]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material.019']} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.766}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.762, 0, 0.87]} rotation={[0, -0.689, 0]} scale={0.245}>
            <group position={[-0.781, 2.471, -0.963]} rotation={[-Math.PI, -0.75, -Math.PI / 2]} scale={0.122}>
              <mesh geometry={nodes.Object_74_1.geometry} material={materials.Plastic} />
              <mesh geometry={nodes.Object_76_1.geometry} material={materials.ShinyPlastic} />
            </group>
            <group position={[0.487, 2.471, -1.148]} rotation={[Math.PI, 0.453, -Math.PI / 2]} scale={0.122}>
              <mesh geometry={nodes.Object_79_1.geometry} material={materials.Plastic} />
              <mesh geometry={nodes.Object_81_1.geometry} material={materials.ShinyPlastic} />
            </group>
            <group position={[1.064, 2.471, 0.037]} rotation={[Math.PI, 1.119, -Math.PI / 2]} scale={0.122}>
              <mesh geometry={nodes.Object_84_1.geometry} material={materials.Plastic} />
              <mesh geometry={nodes.Object_86_1.geometry} material={materials.ShinyPlastic} />
            </group>
            <group position={[0.08, 2.471, 0.905]} rotation={[0, 0.998, Math.PI / 2]} scale={0.122}>
              <mesh geometry={nodes.Object_89_1.geometry} material={materials.Plastic} />
              <mesh geometry={nodes.Object_91_1.geometry} material={materials.ShinyPlastic} />
            </group>
            <group position={[-1.049, 2.471, 0.283]} rotation={[0, -1.172, Math.PI / 2]} scale={0.122}>
              <mesh geometry={nodes.Object_94_1.geometry} material={materials.Plastic} />
              <mesh geometry={nodes.Object_96_1.geometry} material={materials.ShinyPlastic} />
            </group>
            <mesh geometry={nodes.Object_99_1.geometry} material={materials.Plastic} position={[0.913, 3.713, -0.653]} rotation={[-0.039, -0.822, -0.029]} />
            <mesh geometry={nodes.Object_102_1.geometry} material={materials.LeatherCougar2} position={[0.51, 3.859, -0.727]} rotation={[0.061, -0.821, 0.044]} scale={0.312} />
            <mesh geometry={nodes.Object_105_1.geometry} material={materials.Plastic} position={[-0.168, 2.214, -0.072]} rotation={[0, -0.822, 0]} />
            <mesh geometry={nodes.Object_108_1.geometry} material={materials.LeatherCougar} position={[0.213, 2.089, -0.426]} rotation={[-0.295, -0.8, -0.214]} />
            <mesh geometry={nodes.Object_111_1.geometry} material={materials.Plastic} position={[-0.168, 1.22, -0.072]} rotation={[0, -0.822, 0]} />
            <mesh geometry={nodes.Object_114_1.geometry} material={materials.Metallic} position={[-0.168, 0.549, -0.072]} rotation={[0, -0.822, 0]} scale={0.57} />
            <mesh geometry={nodes.Object_117_1.geometry} material={materials.Plastic} position={[-0.168, 2.214, -0.072]} rotation={[0, -0.822, 0]} scale={0.166} />
            <mesh geometry={nodes.Object_120_1.geometry} material={materials.Plastic} position={[0.599, 1.502, 0.544]} rotation={[0, -0.551, 0]} scale={0.04} />
            <mesh geometry={nodes.Object_123_1.geometry} material={materials.Plastic} position={[-0.321, 1.105, 0.07]} rotation={[-0.471, -0.764, -0.339]} />
            <mesh geometry={nodes.Object_126_1.geometry} material={materials.Plastic} position={[-0.051, 0.738, -0.181]} rotation={[0, -0.822, 0]} />
            <group position={[-0.168, 2.214, -0.072]} rotation={[Math.PI / 2, 0, 0.822]}>
              <mesh geometry={nodes.Object_129_1.geometry} material={materials.Leather} />
              <mesh geometry={nodes.Object_131_1.geometry} material={materials.Orange} />
              <mesh geometry={nodes.Object_133_1.geometry} material={materials['Leather.001']} />
              <mesh geometry={nodes.Object_135_1.geometry} material={materials['Leather.002']} />
            </group>
            <mesh geometry={nodes.Object_138_1.geometry} material={materials.Belt} position={[-0.168, 2.214, -0.072]} rotation={[Math.PI / 2, 0, 0.822]} scale={0.996} />
            <mesh geometry={nodes.Object_141_1.geometry} material={materials.Belt} position={[0.304, 2.214, 0.435]} rotation={[Math.PI / 2, 0, 0.822]} scale={0.996} />
            <group position={[-0.168, 2.214, -0.072]} rotation={[0, -0.822, 0]}>
              <mesh geometry={nodes.Object_145_1.geometry} material={materials.Plastic} position={[0, 0.051, 0]} />
              <mesh geometry={nodes.Object_148_1.geometry} material={materials.Plastic} position={[0, 0.038, 0.432]} scale={0.058} />
              <mesh geometry={nodes.Object_151_1.geometry} material={materials.Plastic} position={[0.016, 0.581, 0.432]} />
              <mesh geometry={nodes.Object_154_1.geometry} material={materials['Metallic.001']} position={[0.003, 1.595, -1.295]} rotation={[0, 0.023, 0]} scale={0.009} />
              <mesh geometry={nodes.Object_157_1.geometry} material={materials.Plastic} position={[0.363, 1.275, -1.25]} rotation={[-0.196, 0.026, -0.02]} />
              <mesh geometry={nodes.Object_160_1.geometry} material={materials.Plastic} position={[0.363, 1.275, -1.25]} rotation={[-0.196, 0.026, -0.02]} scale={0.977} />
              <mesh geometry={nodes.Object_163_1.geometry} material={materials.Plastic} position={[-0.329, 1.272, -1.252]} rotation={[-0.196, 0.026, -0.02]} />
              <mesh geometry={nodes.Object_166_1.geometry} material={materials.Plastic} position={[-0.329, 1.272, -1.252]} rotation={[-0.196, 0.026, -0.02]} scale={0.977} />
              <mesh geometry={nodes.Object_169_1.geometry} material={materials.Plastic} position={[0, 0.205, 0]} />
              <mesh geometry={nodes.Object_176_1.geometry} material={materials.Belt} position={[0.304, 1.528, 0.025]} rotation={[Math.PI / 2, 0, 0.051]} />
              <mesh geometry={nodes.Object_179_1.geometry} material={materials.Belt} position={[0.009, 1.646, -1.177]} rotation={[Math.PI / 2, 0, 0.051]} scale={0.03} />
              <mesh geometry={nodes.Object_171_1.geometry} material={materials.Leather} />
              <mesh geometry={nodes.Object_173_1.geometry} material={materials.Orange} />
            </group>
          </group>
        </group>
      </group>
      <group position={[2.115, 0, -3.69]} rotation={[-Math.PI / 2, 0, 0]} scale={1.057}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_184.geometry} material={materials.Pillow} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.Brown_Wood} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.Blue_Wood} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.Blanket} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.Matress} />
        </group>
      </group>
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.019']} position={[-4.452, 2.697, 2.25]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.019']} position={[-4.443, 2.688, 2.256]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.019']} position={[-4.52, 2.669, 2.267]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.019']} position={[-4.485, 2.669, 2.256]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Material.019']} position={[-4.377, 2.691, 2.239]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.019']} position={[-4.403, 2.687, 2.298]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.019']} position={[-4.291, 2.672, 2.235]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['Material.019']} position={[-4.461, 2.712, 2.255]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials['Material.019']} position={[-4.372, 2.676, 2.282]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['Material.019']} position={[-4.29, 2.671, 2.238]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['Material.019']} position={[-4.44, 2.665, 2.263]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.019']} position={[-4.556, 2.668, 2.258]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Material.020']} position={[-4.43, 2.718, 2.258]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.099, 0.099, 0.099]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials['Material.017']} scale={5.971} />
      <mesh geometry={nodes.Object_196.geometry} material={materials['Material.002']} scale={5.971} />
      <mesh geometry={nodes.Object_198.geometry} material={materials['Material.010']} position={[0, 0, -1.088]} scale={5.971} />
      <mesh geometry={nodes.Object_200.geometry} material={materials['Material.021']} position={[0, 9.046, -0.712]} scale={[5.971, 5.971, 6.273]} />
      <mesh geometry={nodes.Object_202.geometry} material={materials['Material.001']} scale={5.971} />
      <mesh geometry={nodes.Object_204.geometry} material={materials['Material.003']} position={[-4.592, 2.645, 3.278]} scale={[1.546, 1, 2.244]} />
      <mesh geometry={nodes.Object_206.geometry} material={materials['Material.004']} position={[-5.971, 6.577, -3.264]} rotation={[0, 0, -Math.PI / 2]} scale={[0.515, 0.529, 0.452]} />
      <mesh geometry={nodes.Object_208.geometry} material={materials['Material.004']} position={[-5.971, 7.159, -4.425]} rotation={[0, 0, -Math.PI / 2]} scale={[0.325, 0.334, 0.285]} />
      <mesh geometry={nodes.Object_210.geometry} material={materials['Material.004']} position={[-5.971, 5.94, -4.425]} rotation={[0, 0, -Math.PI / 2]} scale={[0.453, 0.466, 0.398]} />
      <mesh geometry={nodes.Object_212.geometry} material={materials['Material.008']} position={[-5.971, 5.592, 3.201]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_214.geometry} material={materials['Material.005']} position={[-5.971, 5.752, 3.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_216.geometry} material={materials['Material.006']} position={[-5.971, 5.752, 2.961]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_218.geometry} material={materials['Material.007']} position={[-5.971, 5.272, 3.201]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_220.geometry} material={materials['Material.008']} position={[-5.971, 5.379, 2.77]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_222.geometry} material={materials['Material.005']} position={[-5.971, 5.219, 3.01]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_224.geometry} material={materials['Material.006']} position={[-5.971, 5.219, 2.53]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_226.geometry} material={materials['Material.007']} position={[-5.971, 5.699, 2.77]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_228.geometry} material={materials['Material.008']} position={[-5.971, 5.592, 2.316]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_230.geometry} material={materials['Material.005']} position={[-5.971, 5.752, 2.556]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_232.geometry} material={materials['Material.006']} position={[-5.971, 5.752, 2.076]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_234.geometry} material={materials['Material.007']} position={[-5.971, 5.272, 2.317]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_236.geometry} material={materials['Material.008']} position={[-5.971, 5.379, 1.897]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_238.geometry} material={materials['Material.005']} position={[-5.971, 5.219, 2.137]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_240.geometry} material={materials['Material.006']} position={[-5.971, 5.219, 1.657]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_242.geometry} material={materials['Material.007']} position={[-5.971, 5.699, 1.898]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_244.geometry} material={materials['Material.008']} position={[-5.971, 5.592, 1.459]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_246.geometry} material={materials['Material.005']} position={[-5.971, 5.752, 1.698]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_248.geometry} material={materials['Material.006']} position={[-5.971, 5.752, 1.219]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_250.geometry} material={materials['Material.007']} position={[-5.971, 5.272, 1.459]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_252.geometry} material={materials['Material.008']} position={[-5.971, 5.379, 1.02]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_254.geometry} material={materials['Material.005']} position={[-5.971, 5.219, 1.259]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_256.geometry} material={materials['Material.006']} position={[-5.971, 5.219, 0.78]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_258.geometry} material={materials['Material.007']} position={[-5.971, 5.699, 1.02]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_260.geometry} material={materials['Material.008']} position={[-5.971, 5.592, 0.57]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_262.geometry} material={materials['Material.005']} position={[-5.971, 5.752, 0.809]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_264.geometry} material={materials['Material.006']} position={[-5.971, 5.752, 0.33]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_266.geometry} material={materials['Material.007']} position={[-5.971, 5.272, 0.57]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_268.geometry} material={materials['Material.008']} position={[-5.971, 5.379, 0.121]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_270.geometry} material={materials['Material.005']} position={[-5.971, 5.219, 0.361]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_272.geometry} material={materials['Material.006']} position={[-5.971, 5.219, -0.119]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_274.geometry} material={materials['Material.007']} position={[-5.971, 5.699, 0.122]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_276.geometry} material={materials['Material.008']} position={[-5.971, 4.834, 0.121]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_278.geometry} material={materials['Material.005']} position={[-5.971, 4.994, 0.361]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_280.geometry} material={materials['Material.006']} position={[-5.971, 4.994, -0.119]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_282.geometry} material={materials['Material.007']} position={[-5.971, 4.514, 0.122]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_284.geometry} material={materials['Material.008']} position={[-5.971, 4.542, -0.3]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_286.geometry} material={materials['Material.005']} position={[-5.971, 4.383, -0.06]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_288.geometry} material={materials['Material.006']} position={[-5.971, 4.383, -0.54]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_290.geometry} material={materials['Material.007']} position={[-5.971, 4.862, -0.299]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_292.geometry} material={materials['Material.008']} position={[-5.971, 3.943, -0.379]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_294.geometry} material={materials['Material.005']} position={[-5.971, 4.103, -0.139]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_296.geometry} material={materials['Material.006']} position={[-5.971, 4.103, -0.619]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_298.geometry} material={materials['Material.007']} position={[-5.971, 3.623, -0.378]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_300.geometry} material={materials['Material.008']} position={[-5.971, 3.612, -0.743]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_302.geometry} material={materials['Material.005']} position={[-5.971, 3.452, -0.504]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_304.geometry} material={materials['Material.006']} position={[-5.971, 3.452, -0.983]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_306.geometry} material={materials['Material.007']} position={[-5.971, 3.932, -0.743]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_308.geometry} material={materials['Material.008']} position={[-5.971, 3.098, -0.743]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_310.geometry} material={materials['Material.005']} position={[-5.971, 3.258, -0.503]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_312.geometry} material={materials['Material.006']} position={[-5.971, 3.258, -0.983]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_314.geometry} material={materials['Material.007']} position={[-5.971, 2.779, -0.743]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_316.geometry} material={materials['Material.008']} position={[-5.971, 2.801, -1.159]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_318.geometry} material={materials['Material.005']} position={[-5.971, 2.641, -0.919]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_320.geometry} material={materials['Material.006']} position={[-5.971, 2.641, -1.399]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_322.geometry} material={materials['Material.007']} position={[-5.971, 3.121, -1.159]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_324.geometry} material={materials['Material.008']} position={[-5.971, 2.245, -1.151]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_326.geometry} material={materials['Material.005']} position={[-5.971, 2.404, -0.911]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_328.geometry} material={materials['Material.006']} position={[-5.971, 2.404, -1.391]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_330.geometry} material={materials['Material.007']} position={[-5.971, 1.925, -1.15]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_332.geometry} material={materials['Material.008']} position={[-5.971, 2.034, -1.598]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_334.geometry} material={materials['Material.005']} position={[-5.971, 1.874, -1.359]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_336.geometry} material={materials['Material.006']} position={[-5.971, 1.874, -1.838]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_338.geometry} material={materials['Material.007']} position={[-5.971, 2.354, -1.598]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_340.geometry} material={materials['Material.008']} position={[-5.971, 2.25, -2.065]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_342.geometry} material={materials['Material.005']} position={[-5.971, 2.41, -1.826]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_344.geometry} material={materials['Material.006']} position={[-5.971, 2.41, -2.305]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_346.geometry} material={materials['Material.007']} position={[-5.971, 1.93, -2.065]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_348.geometry} material={materials['Material.008']} position={[-5.971, 2.037, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_350.geometry} material={materials['Material.005']} position={[-5.971, 1.877, -2.289]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_352.geometry} material={materials['Material.006']} position={[-5.971, 1.877, -2.769]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_354.geometry} material={materials['Material.007']} position={[-5.971, 2.357, -2.529]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_356.geometry} material={materials['Material.008']} position={[-5.971, 2.25, -2.98]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_358.geometry} material={materials['Material.005']} position={[-5.971, 2.41, -2.74]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_360.geometry} material={materials['Material.006']} position={[-5.971, 2.41, -3.22]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_362.geometry} material={materials['Material.007']} position={[-5.971, 1.93, -2.979]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_364.geometry} material={materials['Material.008']} position={[-5.971, 2.037, -3.422]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_366.geometry} material={materials['Material.005']} position={[-5.971, 1.877, -3.182]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_368.geometry} material={materials['Material.006']} position={[-5.971, 1.877, -3.662]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_370.geometry} material={materials['Material.007']} position={[-5.971, 2.357, -3.421]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_372.geometry} material={materials['Material.008']} position={[-5.971, 2.25, -3.896]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_374.geometry} material={materials['Material.005']} position={[-5.971, 2.41, -3.656]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_376.geometry} material={materials['Material.006']} position={[-5.971, 2.41, -4.136]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_378.geometry} material={materials['Material.007']} position={[-5.971, 1.93, -3.895]} rotation={[0, 0, -Math.PI / 2]} scale={0.32} />
      <mesh geometry={nodes.Object_380.geometry} material={materials['Material.008']} position={[-5.971, 2.037, -4.366]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_382.geometry} material={materials['Material.005']} position={[-5.971, 1.877, -4.126]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_384.geometry} material={materials['Material.006']} position={[-5.971, 1.877, -4.606]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_386.geometry} material={materials['Material.007']} position={[-5.971, 2.357, -4.366]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, 0.32, 0.32]} />
      <mesh geometry={nodes.Object_388.geometry} material={materials['Material.009']} position={[0, 0, -1.088]} scale={5.971} />
      <mesh geometry={nodes.Object_390.geometry} material={materials['Material.010']} position={[0, 0, -1.088]} scale={5.971} />
      <mesh geometry={nodes.Object_392.geometry} material={materials['Material.010']} position={[0, 0, -1.088]} scale={5.971} />
      <mesh geometry={nodes.Object_394.geometry} material={materials['Material.014']} position={[-2.338, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_396.geometry} material={materials['Material.015']} position={[0.397, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_398.geometry} material={materials['Material.016']} position={[3.28, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_400.geometry} material={materials['Material.011']} position={[-2.338, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_402.geometry} material={materials['Material.012']} position={[0.397, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_404.geometry} material={materials['Material.013']} position={[3.28, 8.703, -6.482]} scale={[0.391, 0.087, 0.391]} />
      <mesh geometry={nodes.Object_406.geometry} material={materials['Material.026']} position={[-5.526, 6.441, -3.344]} rotation={[0, 0, -1.398]} scale={[0.414, 0.323, 0.323]} />
      <mesh geometry={nodes.Object_408.geometry} material={materials['Material.022']} position={[-5.526, 6.441, -3.344]} rotation={[0, 0, -1.398]} scale={[0.414, 0.323, 0.323]} />
      <mesh geometry={nodes.Object_410.geometry} material={materials['Material.027']} position={[-5.704, 7.068, -4.484]} rotation={[0, 0, -1.398]} scale={[0.252, 0.196, 0.196]} />
      <mesh geometry={nodes.Object_412.geometry} material={materials['Material.023']} position={[-5.704, 7.068, -4.484]} rotation={[0, 0, -1.398]} scale={[0.252, 0.196, 0.196]} />
      <mesh geometry={nodes.Object_414.geometry} material={materials['Material.025']} position={[-5.637, 5.771, -4.484]} rotation={[0, 0, -1.398]} scale={[0.329, 0.257, 0.257]} />
      <mesh geometry={nodes.Object_416.geometry} material={materials['Material.024']} position={[-5.637, 5.771, -4.484]} rotation={[0, 0, -1.398]} scale={[0.329, 0.257, 0.257]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
